# Generated by Django 2.1.5 on 2019-01-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=20)),
                ('pool_id', models.CharField(help_text='The name of the pooled library, may be a sample ID or tube ID', max_length=30, null=True)),
                ('sample_id', models.CharField(help_text='Individual component identifiers, may be index names or other customer provided name.', max_length=30)),
                ('i7_index_name', models.CharField(max_length=30, null=True)),
                ('i5_index_name', models.CharField(max_length=30, null=True)),
                ('i7_index_sequence', models.CharField(max_length=40, null=True)),
                ('i5_index_sequence', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=20)),
                ('pool_id', models.CharField(help_text='The name of the pooled library, may be a sample ID or tube ID', max_length=30, null=True)),
                ('sample_id', models.CharField(help_text='Individual component identifiers, should map to customer provided name.', max_length=30)),
                ('flowcell_id', models.CharField(help_text='Unique illumina flowcell the sample was run on.', max_length=40)),
                ('lane', models.CharField(max_length=30)),
                ('read', models.CharField(max_length=30)),
                ('i7_index_sequence', models.CharField(max_length=40)),
                ('i5_index_sequence', models.CharField(max_length=40, null=True)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=20)),
                ('exec_date', models.DateTimeField()),
                ('exec_status', models.CharField(choices=[('INIT', 'Initial State'), ('OK', 'OK'), ('FAIL', 'Fail')], default='INIT', max_length=4)),
                ('fail_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TubeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=20)),
                ('tube_id', models.CharField(max_length=40)),
                ('pool_id', models.CharField(help_text='The name of the pooled library, may be a sample ID or tube ID', max_length=30, null=True)),
                ('volume', models.CharField(max_length=40, null=True)),
                ('concentration', models.CharField(max_length=40, null=True)),
                ('total_amount', models.CharField(max_length=40, null=True)),
                ('quantitation_method', models.CharField(max_length=40, null=True)),
                ('buffer', models.CharField(max_length=40, null=True)),
                ('organism', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
