# Generated by Django 2.1.5 on 2019-01-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=20)),
                ('website_order_id', models.CharField(default='0', max_length=20)),
                ('analysis_type', models.CharField(choices=[('FQC', 'FastQC'), ('MQC', 'MultiQC'), ('QD', 'Enqueing')], default='FQC', max_length=10)),
                ('exec_date', models.DateTimeField()),
                ('exec_status', models.CharField(choices=[('INIT', 'Initial State'), ('ENQD', 'Enqueued'), ('OK', 'OK'), ('FAIL', 'Fail')], default='INIT', max_length=4)),
                ('details', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
